### ISSUE TITLE
Server not reachable

### ISSUE THREAD

**Issue by AzisPT** [festivaldev/Paradise#3]
I have tested with my dns, local ip, and external ip, firewall is off and ports are open, what should I do?

![Screenshot_329](https://user-images.githubusercontent.com/39005891/198832201-1c39560e-a612-448a-8e3a-9b96989531d6.png)
![Screenshot_330](https://user-images.githubusercontent.com/39005891/198832211-4202a95b-042f-4025-9007-d8e2d971c0bc.png)

**Comment by SniperGER** [comment]
Hi there!

Thank you for your interest in hosting your own server! I'm very happy to see someone else using Paradise for their own server!

So, first of all: have you checked that Photon and the Paradise Photon application are actually running? There should be logs in `Paradise.Realtime/logs` and `photon/log` and the PhotonControl icon (if running) should show a blue circle.

`Photon-2022xxxx.log`, `PhotonCLR.log` and `Photon-ParadiseApplication-2022xxxx.log` may also contain errors. You could delete them, restart everything Photon related and upload the logs here so I can analyze them.

**Comment by AzisPT** [comment]
So I basically can't run the photon from the `\Paradise.Realtime\bin` I can only run it from `\Photon-OnPremise-Server-SDK_v4-0-29-11263` 

But with the `\Photon-OnPremise-Server-SDK_v4-0-29-11263` I've managed to run the Comms Server, but the Game Server just stays at "Refreshing Server".

Logs from the server `\Paradise.Realtime\bin`
[PhotonCLR.log](https://github.com/festivaldev/Paradise/files/9893906/PhotonCLR.log)
[Photon-LoadBalancing-20221029.log](https://github.com/festivaldev/Paradise/files/9893907/Photon-LoadBalancing-20221029.log)
Logs from the `\Photon-OnPremise-Server-SDK_v4-0-29-11263`
[PhotonCLR.log](https://github.com/festivaldev/Paradise/files/9893911/PhotonCLR.log)
[Photon-LoadBalancing-20221029.log](https://github.com/festivaldev/Paradise/files/9893912/Photon-LoadBalancing-20221029.log)

**Comment by SniperGER** [comment]
I'm a little confused here about that LoadBalancing stuff. Usually there should be the Paradise.Realtime folder (containing `bin` and `logs`) next to a folder called "photon" (basically just `Photon-OnPremise-Server-SDK_v4-0-29-11263/Bin64`, just renamed).

Also, you need the PhotonServer.config found in the repo's root (did I forget to put this into the release zip?) which doesn't contain any LoadBalancing applications.

**Comment by AzisPT** [comment]
This is what I have in the folder
![Screenshot_332](https://user-images.githubusercontent.com/39005891/198839442-fc3d1856-bd72-4ca7-8455-51a588ecaa79.png)

**Comment by AzisPT** [comment]
I don't seem to find the `PhotonServer.config` besides the one that Photon already bring with it

**Comment by SniperGER** [comment]
The missing `logs` folder suggests that the Realtime server hasn't been actually running.

Could you show the contents of the other folders as well?

For the PhotonServer.config, just use this one: https://github.com/festivaldev/Paradise/blob/new-paradise/PhotonServer.config  
Don't forget to restart PhotonControl if it's already running.

**Comment by AzisPT** [comment]
The `logs` does not exist because I was not being able to start the `bin` Photon, only the `\Photon-OnPremise-Server-SDK_v4-0-29-11263`

Now I started it and it closed unexpectedly logs below.
[Photon-ParadiseApplication-20221029.log](https://github.com/festivaldev/Paradise/files/9893979/Photon-ParadiseApplication-20221029.log)

As for the other folders here's the content:

![Screenshot_333](https://user-images.githubusercontent.com/39005891/198839969-0abe8c95-8bb0-4725-bc3d-d06ec133b74e.png)
![Screenshot_334](https://user-images.githubusercontent.com/39005891/198839970-2ee10585-dd47-44a4-8d96-8a539191787b.png)

**Comment by AzisPT** [comment]
So I managed to put it working by running `PhotonSocketServer.exe /install LoadBalancing` i nthe cmd (while in the cd of the server)

**Comment by SniperGER** [comment]
Photon isn't started from the `bin` folder directly, but from  `photon\PhotonControl.exe` (same folder where the updated PhotonServer.config should be stored), which apparently you already figured out.

Did you copy the required dependencies as lined out in the installation instructions?

Also, if available, could you upload your current log files from `photon/log`? These may contain more info as to why the application is crashing.

**Comment by AzisPT** [comment]
The application is now working and I went inside the game, but I saw some strange bugs.

Here we can see the weapon, but no crosshair.
![Screenshot_336](https://user-images.githubusercontent.com/39005891/198842452-412fe733-6417-48e7-a899-ef8cbb45221c.png)
And when we zoom with it there's no crosshair as well.
![Screenshot_337](https://user-images.githubusercontent.com/39005891/198842469-6c612471-3c33-4f7d-96ce-6db0b9a2a17e.png)

Is this normal in this build?

**Comment by SniperGER** [comment]
Great to hear your server is working now!

About the missing scope/crosshair: it looks like the shop is configured incorrectly. I personally never used these weapons so I don't know what they're supposed to look like. I've asked the team to verify if this behavior also applies to other weapons as well, so this will probably be fixed soon.

**Comment by AzisPT** [comment]
Okay thank you for your help :)
